### ISSUE TITLE
Upload User guide.

### ISSUE THREAD

**Issue by yanprosobo** [AY1920S1-CS2113-T16-2/main#114]
Hi, i will be testing your application later. Is there an updated user guide that you could upload to this repo so i can have reference to all the commands available? Thank you.

**Comment by yanprosobo** [comment]
the one on the repo now is empty @ https://github.com/AY1920S1-CS2113-T16-2/main/blob/master/docs/UserGuide.adoc

**Comment by shaun97** [comment]
uploaded.

**Comment by yanprosobo** [comment]
Thank you.
Commit 817a167 closes: #114
